# Generated by Django 5.0.1 on 2025-05-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.DateField(),
        ),
    ]
